import { pacificOpenMs } from "../format";
import type { Agent, AuditEntry, ConnectedApp, InterceptRecord, Policy } from "./types";

export const agents: Agent[] = [
  {
    id: "support-copilot",
    name: "Support Copilot",
    role: "support",
    description: "Triages inbound Gmail through MCP. Tool results are minimized before they reach the model.",
    allowedApps: ["gmail", "slack", "notion", "github"],
  },
  {
    id: "ops-autopilot",
    name: "Ops Autopilot",
    role: "ops",
    description: "Weekly ops over MCP tools: GitHub, Slack, Notion, Gmail — every call through Aegis, PII stripped for the model.",
    allowedApps: ["gmail", "slack", "notion", "github"],
  },
  {
    id: "code-agent",
    name: "Codebase Agent",
    role: "engineering",
    description: "Reviews diffs, comments on PRs, and requests merge after CI.",
    allowedApps: ["github", "slack", "notion"],
  },
  {
    id: "outreach-bot",
    name: "Outreach Bot",
    role: "sales",
    description: "Drafts and sends customer email. Tightly gated for outbound send.",
    allowedApps: ["gmail", "slack"],
  },
];

export const policies: Policy[] = [
  {
    id: "pol-block-injection",
    name: "Block prompt injection",
    description: "Deny any action whose payload tries to override instructions or bypass the trust layer.",
    enabled: true,
    priority: 110,
    condition: { promptInjection: true },
    decision: "deny",
  },
  {
    id: "pol-block-secrets",
    name: "Secrets never reach the model",
    description: "Deny send/post/write that matches API keys or financial secrets. The raw value is never forwarded to the model.",
    enabled: true,
    priority: 100,
    condition: {
      actions: ["send", "post", "write", "alert"],
      sensitiveContent: true,
    },
    decision: "deny",
  },
  {
    id: "pol-no-agent-policy-edits",
    name: "Agents cannot edit policies",
    description: "Notion Policies database is human-owned.",
    enabled: true,
    priority: 95,
    condition: { apps: ["notion"], actions: ["write"], databases: ["Policies"] },
    decision: "deny",
  },
  {
    id: "pol-github-merge",
    name: "Human merge for every PR",
    description: "GitHub merges always require an approver in Slack.",
    enabled: true,
    priority: 90,
    condition: { apps: ["github"], actions: ["merge"] },
    decision: "require_approval",
  },
  {
    id: "pol-mass-email",
    name: "Hold bulk Gmail sends",
    description: "Eight or more recipients must be approved. Recipient lists are minimized before the model sees them.",
    enabled: true,
    priority: 80,
    condition: { apps: ["gmail"], actions: ["send"], minRecipients: 8 },
    decision: "require_approval",
  },
  {
    id: "pol-external-email",
    name: "Hold external Gmail sends",
    description: "Mail leaving the company domain needs a human.",
    enabled: true,
    priority: 75,
    condition: { apps: ["gmail"], actions: ["send"], externalRecipients: true },
    decision: "require_approval",
  },
  {
    id: "pol-slack-general",
    name: "Hold #general posts",
    description: "Company-wide Slack posts require approval.",
    enabled: true,
    priority: 70,
    condition: { apps: ["slack"], actions: ["post"], channels: ["#general"] },
    decision: "require_approval",
  },
  {
    id: "pol-allow-reads",
    name: "Allow reads and drafts",
    description: "Non-executing actions proceed with logging. Returned tool data is still minimized.",
    enabled: true,
    priority: 20,
    condition: { actions: ["read", "draft", "comment", "append"] },
    decision: "allow",
  },
  {
    id: "pol-support-slack",
    name: "Support may post to #support",
    description: "Support Copilot can notify the support channel without a hold.",
    enabled: true,
    priority: 40,
    condition: {
      apps: ["slack"],
      actions: ["post", "alert"],
      agentRoles: ["support"],
      channels: ["#support"],
    },
    decision: "allow",
  },
  {
    id: "pol-minimize-pii",
    name: "Redact PII before the model",
    description: "Emails, phones, and SSNs are stripped from tool results so the model never sees them.",
    enabled: true,
    priority: 45,
    condition: { dataClasses: ["email", "phone", "ssn"] },
    decision: "allow",
    minimize: "redact",
  },
  {
    id: "pol-hash-ips",
    name: "Hash IP addresses",
    description: "Network addresses are hashed rather than dropped, so ops can still correlate events.",
    enabled: true,
    priority: 44,
    condition: { dataClasses: ["ip"] },
    decision: "allow",
    minimize: "hash",
  },
  {
    id: "pol-ops-engineering-slack",
    name: "Ops may post to #engineering",
    description: "Ops Autopilot can notify engineering without a hold.",
    enabled: true,
    priority: 40,
    condition: {
      apps: ["slack"],
      actions: ["post", "alert"],
      agentRoles: ["ops"],
      channels: ["#engineering"],
    },
    decision: "allow",
  },
];

export function connectedApps(now: string): ConnectedApp[] {
  return [
    {
      id: "gmail",
      name: "Gmail",
      status: "disconnected",
      description: "MCP Gmail. Reads are minimized before they reach the model; sends are gated.",
      lastSyncAt: now,
      capabilities: ["read", "draft", "send"],
      oauthConfigured: false,
    },
    {
      id: "slack",
      name: "Slack",
      status: "disconnected",
      description: "MCP Slack. Approval cards, deny alerts, and minimized channel context.",
      lastSyncAt: now,
      capabilities: ["approvals", "alerts", "notifications"],
      oauthConfigured: false,
    },
    {
      id: "notion",
      name: "Notion",
      status: "disconnected",
      description: "MCP Notion. Policy hub stays human-owned; audit logs stay append-only.",
      lastSyncAt: now,
      capabilities: ["policies", "approvals", "audit-logs"],
      oauthConfigured: false,
    },
    {
      id: "github",
      name: "GitHub",
      status: "disconnected",
      description: "MCP GitHub. Comments can ship. Merges wait. Diffs are minimized for the model.",
      lastSyncAt: now,
      capabilities: ["read", "comment", "merge-gate"],
      oauthConfigured: false,
    },
  ];
}

export function seedHistory(now: number): {
  intercepts: InterceptRecord[];
  audit: AuditEntry[];
} {
  const open = pacificOpenMs(now);
  const t = (minsAfterOpen: number) => new Date(open + minsAfterOpen * 60_000).toISOString();

  const intercepts: InterceptRecord[] = [
    {
      id: "int-seed-1",
      createdAt: t(1),
      agentId: "support-copilot",
      app: "gmail",
      action: "read",
      summary: "Read 12 unread support threads in billing@",
      payload: { to: ["billing@acme.internal"] },
      verdict: {
        decision: "allow",
        riskScore: 8,
        riskLevel: "low",
        reasons: ["Read-only inbox access."],
        matchedPolicyIds: ["pol-allow-reads"],
        signals: [],
        steps: [],
      },
      status: "executed",
      decidedAt: t(1),
      decidedBy: "aegis",
    },
    {
      id: "int-seed-2",
      createdAt: t(2),
      agentId: "support-copilot",
      app: "gmail",
      action: "draft",
      summary: "Draft refund reply for order 18422",
      payload: {
        to: ["casey@gmail.com"],
        subject: "Re: Refund for order 18422",
        body: "Hi Casey, we can process a refund to the original payment method within 3 days.",
      },
      verdict: {
        decision: "allow",
        riskScore: 14,
        riskLevel: "low",
        reasons: ["Drafts do not send."],
        matchedPolicyIds: ["pol-allow-reads"],
        signals: [],
        steps: [],
      },
      status: "executed",
      decidedAt: t(2),
      decidedBy: "aegis",
    },
    {
      id: "int-seed-3",
      createdAt: t(3),
      agentId: "code-agent",
      app: "github",
      action: "comment",
      summary: "Comment on PR #418 — missing migration rollback",
      payload: {
        repo: "acme/billing-api",
        prNumber: 418,
        content: "This migration needs a down() before merge.",
      },
      verdict: {
        decision: "allow",
        riskScore: 10,
        riskLevel: "low",
        reasons: ["Comments are reversible."],
        matchedPolicyIds: ["pol-allow-reads"],
        signals: [],
        steps: [],
      },
      status: "executed",
      decidedAt: t(3),
      decidedBy: "aegis",
    },
    {
      id: "int-seed-4",
      createdAt: t(4),
      agentId: "outreach-bot",
      app: "gmail",
      action: "send",
      summary: "Send Q3 promo to 24 external leads",
      payload: {
        to: Array.from({ length: 24 }, (_, i) => `lead${i}@gmail.com`),
        subject: "A note from Acme",
        body: "Quick note about our Q3 plan.",
      },
      verdict: {
        decision: "require_approval",
        riskScore: 62,
        riskLevel: "high",
        reasons: ["Bulk external send held by policy."],
        matchedPolicyIds: ["pol-mass-email"],
        signals: [],
        steps: [],
      },
      status: "pending",
    },
  ];

  const audit: AuditEntry[] = [
    {
      id: "aud-1",
      at: t(1),
      interceptId: "int-seed-1",
      event: "allowed",
      actor: "aegis",
      app: "gmail",
      summary: "Allowed Gmail read for Support Copilot",
      prevHash: "genesis",
      hash: "a1c4e8",
      notionPageId: "ntn_seed_1",
    },
    {
      id: "aud-2",
      at: t(2),
      interceptId: "int-seed-2",
      event: "allowed",
      actor: "aegis",
      app: "gmail",
      summary: "Allowed Gmail draft for Support Copilot",
      prevHash: "a1c4e8",
      hash: "b92d10",
      notionPageId: "ntn_seed_2",
    },
    {
      id: "aud-3",
      at: t(3),
      interceptId: "int-seed-3",
      event: "allowed",
      actor: "aegis",
      app: "github",
      summary: "Allowed GitHub comment on acme/billing-api#418",
      prevHash: "b92d10",
      hash: "c77aa2",
      notionPageId: "ntn_seed_3",
    },
    {
      id: "aud-4",
      at: t(4),
      interceptId: "int-seed-4",
      event: "held",
      actor: "aegis",
      app: "gmail",
      summary: "Held Outreach Bot mass send — waiting in Slack #aegis-approvals",
      prevHash: "c77aa2",
      hash: "d0f31c",
      notionPageId: "ntn_seed_4",
    },
  ];

  return { intercepts, audit };
}
